-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceExtendedSearch/maintenance/db/sql/bs_extendedsearch_history.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_extendedsearch_history (
  esh_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  esh_user INTEGER NOT NULL,
  esh_term VARCHAR(255) NOT NULL,
  esh_hits INTEGER DEFAULT 0 NOT NULL,
  esh_hits_approximated SMALLINT DEFAULT 0 NOT NULL,
  esh_timestamp BLOB DEFAULT NULL,
  esh_autocorrected SMALLINT DEFAULT 0 NOT NULL,
  esh_lookup CLOB DEFAULT NULL
);
