-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceExtendedSearch/maintenance/db/sql/bs_extendedsearch_trace.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_extendedsearch_trace (
  est_title VARCHAR(255) NOT NULL,
  est_namespace INT NOT NULL,
  est_user INT NOT NULL,
  est_type VARCHAR(255) NOT NULL,
  est_count INT DEFAULT 0 NOT NULL,
  est_last_view BINARY(14) NOT NULL,
  PRIMARY KEY(
    est_title, est_namespace, est_user
  )
) /*$wgDBTableOptions*/;
